### ISSUE TITLE
为什么劫持含sample文件的内容读取到sample文件夹下面

### ISSUE THREAD

**Issue by zhudan** [whyour/qinglong-static#2]
https://github.com/whyour/qinglong-static/blob/bf9b0a1232fb3e6b9e62ca119c29908679afb5d2/build/api/config.js#L60

为什么劫持含sample文件的内容读取到sample文件夹下面，在仓库首页的readme中并没有要求映射sample目录，并且在大部分使用场景中sample内容文件一般是放config目录的，最后就是在下面的保存接口中只是针对了configPath的文件进行提交修改

**Comment by zhudan** [comment]
config_1.default.samplePath 没有指定到/ql/data下面，还是/ql/config

**Comment by whyour** [comment]
https://github.com/whyour/qinglong  项目在这
